#ifndef MAP_WORDS_DEFINITIONS_H_INCLUDED
#define MAP_WORDS_DEFINITIONS_H_INCLUDED

#define NOT_FOUND	0
#define IMPORT		1
#define CLASS		2
#define CLASSNAME	3
#define PRIMITIVE	4
#define IF			5
#define PUBLIC		6
#define PRIVATE		7
#define BRACKET		8
#define STATIC		10



#endif // MAP_WORDS_DEFINITIONS_H_INCLUDED
